version: "3.8"

services:
  bind:
    image: internetsystemsconsortium/bind9:9.18
    container_name: dns-server
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./dns/configs:/etc/bind
    restart: unless-stopped